"""Supported consumer API for the reusable Water Chemistry Engine.

The package root is the compatibility boundary for ordinary consumers.  More
specialized modules remain importable during the pre-1.0 development period,
but applications should prefer the names exported here for deterministic
forward calculation and bounded treatment optimization.
"""

from water_chemistry_engine.alkalinity_balance import (
    AlkalinityBalanceResult,
    AlkalinityModelLimitation,
    BlendedAlkalinityResult,
    FinalAlkalinityResult,
    ModeledAlkalinity,
    ResolvedSourceAlkalinity,
    SourceAlkalinityContribution,
    SourceAlkalinityResolution,
    SourceAlkalinityResolutionMethod,
    TreatmentAlkalinityContribution,
    UnresolvedSourceAlkalinity,
    UnresolvedSourceAlkalinityReason,
)
from water_chemistry_engine.blending import (
    BlendedSource,
    BlendIonContribution,
    BlendIonResolution,
    ResolvedBlendIon,
    UnresolvedBlendIon,
    UnresolvedBlendIonReason,
    WaterBlendResult,
)
from water_chemistry_engine.chemical_state import (
    AqueousChemicalState,
    DerivedIonConcentration,
)
from water_chemistry_engine.comparison_policy import (
    TargetComparisonPolicy,
    TargetIonClosenessPolicy,
)
from water_chemistry_engine.concentrations import (
    ConcentrationRangeEndpoint,
    ExactConcentrationEndpoint,
    IonConcentration,
    IonConcentrationLowerBound,
    IonConcentrationNotDetected,
    IonConcentrationRange,
    IonConcentrationUpperBound,
    IonConcentrationValue,
    LowerBoundConcentrationEndpoint,
    NotDetectedConcentrationEndpoint,
    UpperBoundConcentrationEndpoint,
)
from water_chemistry_engine.contribution_matrix import (
    AlkalinityContributionMatrixRow,
    IonContributionCalculationBasis,
    IonContributionMatrixRow,
    SourceContributionCell,
    SourceContributionCellStatus,
    SourceContributionColumn,
    TreatmentContributionCell,
    TreatmentContributionCellStatus,
    TreatmentContributionColumn,
    WaterContributionMatrix,
)
from water_chemistry_engine.forward_calculator import (
    ForwardSourceResult,
    ForwardWaterCalculationResult,
    ForwardWaterSource,
    calculate_forward_water,
)
from water_chemistry_engine.forward_notices import (
    ForwardCalculationNotice,
    ForwardNoticeCode,
    ForwardNoticeLevel,
)
from water_chemistry_engine.ions import Ion
from water_chemistry_engine.optimization import (
    OptimizerBlendPolicy,
    OptimizerDiagnostic,
    OptimizerDiagnosticCode,
    OptimizerFeasibilityStatus,
    OptimizerInputSupportStatus,
    OptimizerMaterialAddition,
    OptimizerMaterialConstraint,
    OptimizerPlan,
    OptimizerPracticalityStatus,
    OptimizerRequest,
    OptimizerResult,
    OptimizerSolverReport,
    OptimizerSource,
    OptimizerSourceVolume,
    OptimizerStrategy,
    OptimizerTargetFitStatus,
)
from water_chemistry_engine.optimizer_solver import optimize_treatment
from water_chemistry_engine.preparation_instructions import (
    BlendPreparationInstruction,
    SourceVolumeInstruction,
    TreatmentPreparationInstruction,
    WaterPreparationInstructions,
)
from water_chemistry_engine.profiles import SourceWaterProfile
from water_chemistry_engine.quantity_types import ScalarQuantity
from water_chemistry_engine.reported_disinfectants import (
    DisinfectantKind,
    ReportedDisinfectant,
)
from water_chemistry_engine.reported_properties import (
    Alkalinity,
    AlkalinityAnalyticalContext,
    AlkalinityResultIdentity,
    Conductivity,
    ReportedPH,
    ReportingBasis,
    SampleFiltrationState,
    TotalDissolvedSolids,
    TotalHardness,
)
from water_chemistry_engine.reported_statistics import (
    ReportedStatistic,
    ReportedStatisticKind,
)
from water_chemistry_engine.reported_values import SourceResolutionPolicy
from water_chemistry_engine.reporting_context import (
    ObservationPeriod,
    ReportedResultContext,
    ResultCoverage,
    WaterStage,
)
from water_chemistry_engine.source_document import SourceDocumentMetadata
from water_chemistry_engine.source_resolution import (
    ResolvedSourceIon,
    SourceIonResolution,
    SourceIonResolutionMethod,
    SourceProfileResolutionResult,
    UnresolvedSourceIon,
    UnresolvedSourceIonReason,
)
from water_chemistry_engine.target_comparison import (
    TargetAlkalinityComparison,
    TargetAlkalinityComparisonStatus,
    TargetIonCalculationBasis,
    TargetIonClosenessStatus,
    TargetIonComparison,
    TargetIonComparisonStatus,
    TargetPHComparison,
    TargetPHComparisonStatus,
    TargetProfileComparison,
    TargetProfileComparisonStatus,
    UnsupportedTargetIonReason,
)
from water_chemistry_engine.target_profiles import (
    TargetProfileClassification,
    TargetProfileProvenance,
    TargetWaterProfile,
)
from water_chemistry_engine.treatment_application import (
    AppliedTreatment,
    ResolvedTreatmentIon,
    TreatmentAddition,
    TreatmentApplicationResult,
    TreatmentIonContribution,
    TreatmentIonResolution,
    UnresolvedTreatmentIon,
    UnresolvedTreatmentIonReason,
)
from water_chemistry_engine.treatment_ingredients import (
    CALCIUM_CHLORIDE_ANHYDROUS,
    CALCIUM_CHLORIDE_DIHYDRATE,
    EPSOM_SALT,
    GYPSUM,
    POTASSIUM_CHLORIDE,
    SIMPLE_MINERAL_INGREDIENTS,
    SODIUM_BICARBONATE,
    SODIUM_CHLORIDE,
)
from water_chemistry_engine.treatment_materials import (
    ExactMassDosedTreatmentMaterial,
    ExactMassFractionTreatmentMaterial,
    ExactMassPerVolumeDosedSolutionTreatmentMaterial,
    ExactVolumeDosedSolutionTreatmentMaterial,
    RangedMassFractionTreatmentMaterial,
    ResolvedMassPerVolumeSolutionDose,
    ResolvedTreatmentMaterialVolumeDose,
    TreatmentMaterialActiveMassRange,
    TreatmentMaterialForm,
)
from water_chemistry_engine.treatment_stoichiometry import IonContribution
from water_chemistry_engine.water_identity import (
    PhysicalSourceType,
    PhysicalWaterSource,
    WaterIdentity,
    WaterType,
)

__version__ = "0.5.0"

__all__ = [
    "CALCIUM_CHLORIDE_ANHYDROUS",
    "CALCIUM_CHLORIDE_DIHYDRATE",
    "EPSOM_SALT",
    "GYPSUM",
    "POTASSIUM_CHLORIDE",
    "SIMPLE_MINERAL_INGREDIENTS",
    "SODIUM_BICARBONATE",
    "SODIUM_CHLORIDE",
    "Alkalinity",
    "AlkalinityAnalyticalContext",
    "AlkalinityBalanceResult",
    "AlkalinityContributionMatrixRow",
    "AlkalinityModelLimitation",
    "AlkalinityResultIdentity",
    "AppliedTreatment",
    "AqueousChemicalState",
    "BlendIonContribution",
    "BlendIonResolution",
    "BlendPreparationInstruction",
    "BlendedAlkalinityResult",
    "BlendedSource",
    "ConcentrationRangeEndpoint",
    "Conductivity",
    "DerivedIonConcentration",
    "DisinfectantKind",
    "ExactConcentrationEndpoint",
    "ExactMassDosedTreatmentMaterial",
    "ExactMassFractionTreatmentMaterial",
    "ExactMassPerVolumeDosedSolutionTreatmentMaterial",
    "ExactVolumeDosedSolutionTreatmentMaterial",
    "FinalAlkalinityResult",
    "ForwardCalculationNotice",
    "ForwardNoticeCode",
    "ForwardNoticeLevel",
    "ForwardSourceResult",
    "ForwardWaterCalculationResult",
    "ForwardWaterSource",
    "Ion",
    "IonConcentration",
    "IonConcentrationLowerBound",
    "IonConcentrationNotDetected",
    "IonConcentrationRange",
    "IonConcentrationUpperBound",
    "IonConcentrationValue",
    "IonContribution",
    "IonContributionCalculationBasis",
    "IonContributionMatrixRow",
    "LowerBoundConcentrationEndpoint",
    "ModeledAlkalinity",
    "NotDetectedConcentrationEndpoint",
    "ObservationPeriod",
    "OptimizerBlendPolicy",
    "OptimizerDiagnostic",
    "OptimizerDiagnosticCode",
    "OptimizerFeasibilityStatus",
    "OptimizerInputSupportStatus",
    "OptimizerMaterialAddition",
    "OptimizerMaterialConstraint",
    "OptimizerPlan",
    "OptimizerPracticalityStatus",
    "OptimizerRequest",
    "OptimizerResult",
    "OptimizerSolverReport",
    "OptimizerSource",
    "OptimizerSourceVolume",
    "OptimizerStrategy",
    "OptimizerTargetFitStatus",
    "PhysicalSourceType",
    "PhysicalWaterSource",
    "RangedMassFractionTreatmentMaterial",
    "ReportedDisinfectant",
    "ReportedPH",
    "ReportedResultContext",
    "ReportedStatistic",
    "ReportedStatisticKind",
    "ReportingBasis",
    "ResolvedBlendIon",
    "ResolvedMassPerVolumeSolutionDose",
    "ResolvedSourceAlkalinity",
    "ResolvedSourceIon",
    "ResolvedTreatmentIon",
    "ResolvedTreatmentMaterialVolumeDose",
    "ResultCoverage",
    "SampleFiltrationState",
    "ScalarQuantity",
    "SourceAlkalinityContribution",
    "SourceAlkalinityResolution",
    "SourceAlkalinityResolutionMethod",
    "SourceContributionCell",
    "SourceContributionCellStatus",
    "SourceContributionColumn",
    "SourceDocumentMetadata",
    "SourceIonResolution",
    "SourceIonResolutionMethod",
    "SourceProfileResolutionResult",
    "SourceResolutionPolicy",
    "SourceVolumeInstruction",
    "SourceWaterProfile",
    "TargetAlkalinityComparison",
    "TargetAlkalinityComparisonStatus",
    "TargetComparisonPolicy",
    "TargetIonCalculationBasis",
    "TargetIonClosenessPolicy",
    "TargetIonClosenessStatus",
    "TargetIonComparison",
    "TargetIonComparisonStatus",
    "TargetPHComparison",
    "TargetPHComparisonStatus",
    "TargetProfileClassification",
    "TargetProfileComparison",
    "TargetProfileComparisonStatus",
    "TargetProfileProvenance",
    "TargetWaterProfile",
    "TotalDissolvedSolids",
    "TotalHardness",
    "TreatmentAddition",
    "TreatmentAlkalinityContribution",
    "TreatmentApplicationResult",
    "TreatmentContributionCell",
    "TreatmentContributionCellStatus",
    "TreatmentContributionColumn",
    "TreatmentIonContribution",
    "TreatmentIonResolution",
    "TreatmentMaterialActiveMassRange",
    "TreatmentMaterialForm",
    "TreatmentPreparationInstruction",
    "UnresolvedBlendIon",
    "UnresolvedBlendIonReason",
    "UnresolvedSourceAlkalinity",
    "UnresolvedSourceAlkalinityReason",
    "UnresolvedSourceIon",
    "UnresolvedSourceIonReason",
    "UnresolvedTreatmentIon",
    "UnresolvedTreatmentIonReason",
    "UnsupportedTargetIonReason",
    "UpperBoundConcentrationEndpoint",
    "WaterBlendResult",
    "WaterContributionMatrix",
    "WaterIdentity",
    "WaterPreparationInstructions",
    "WaterStage",
    "WaterType",
    "__version__",
    "calculate_forward_water",
    "optimize_treatment",
]
